language: java
jdk: oraclejdk8
sudo: true
dist: trusty
 
script:
  - ./mvnw clean install -B
  - ./mvnw cobertura:cobertura

before_install:
  - chmod +x mvnw

after_success:
 - bash <(curl -s https://codecov.io/bash)
